// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZmeo1O479V6oSDqR2EPNaDVPCOPAdTs',
    appId: '1:541644046737:web:2545e444d598163a8bda30',
    messagingSenderId: '541644046737',
    projectId: 'mentor-match-b99ff',
    authDomain: 'mentor-match-b99ff.firebaseapp.com',
    storageBucket: 'mentor-match-b99ff.appspot.com',
    measurementId: 'G-ZVJETRT95G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPnJk8n0CgmxM-DNvSKpmGPxkOAZjDtBM',
    appId: '1:541644046737:android:8b4ed1d75d9abadf8bda30',
    messagingSenderId: '541644046737',
    projectId: 'mentor-match-b99ff',
    storageBucket: 'mentor-match-b99ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMkFdYxB0sSIBxZViqe-yGlklfq8A4JjA',
    appId: '1:541644046737:ios:2b8718c3dc44c1b38bda30',
    messagingSenderId: '541644046737',
    projectId: 'mentor-match-b99ff',
    storageBucket: 'mentor-match-b99ff.appspot.com',
    iosBundleId: 'com.clc.clc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMkFdYxB0sSIBxZViqe-yGlklfq8A4JjA',
    appId: '1:541644046737:ios:2b8718c3dc44c1b38bda30',
    messagingSenderId: '541644046737',
    projectId: 'mentor-match-b99ff',
    storageBucket: 'mentor-match-b99ff.appspot.com',
    iosBundleId: 'com.clc.clc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjZmeo1O479V6oSDqR2EPNaDVPCOPAdTs',
    appId: '1:541644046737:web:db5df6871b8278cf8bda30',
    messagingSenderId: '541644046737',
    projectId: 'mentor-match-b99ff',
    authDomain: 'mentor-match-b99ff.firebaseapp.com',
    storageBucket: 'mentor-match-b99ff.appspot.com',
    measurementId: 'G-TK7GS04Q7D',
  );
}
